### ISSUE TITLE
Feature: 엔티티 생성

### ISSUE THREAD

**Issue by whereami2048** [Kusitms-29th-Kukathon-F/Backend#2]
## 📝 Content
- 엔티티 생성

## ✅ TODO

- [x] 유저 엔티티 구현
- [x] 선물함 엔티티 구현
- [x] 도파민 점수 엔티티 구현
- [x] 보상 엔티티 구현
- [x] 퀘스트 엔티티 구현
- [x] 시청 시간 엔티티 구현
